Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Enabled: true
  Max: 12

Metrics/CyclomaticComplexity:
  Enabled: true
  Max: 9

Metrics/PerceivedComplexity:
  Enabled: true
  Max: 9

Layout/LineLength:
  Enabled: true
  Max: 198